### PR TITLE
Design Teardown

### PR DESCRIPTION
**Pull request by jabichris**
#### What does this PR do?
This PR consists of building a heatmap of the Smashing Magazine website.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi Team, you have done a great job so far. :slightly_smiling_face:  No markup errors, no CSS validator errors, README looks professional, description commits, pull request has title and summary. :+1: 
There are a few changes required to approve this project, below is the comment:

- Kindly check this [link](https://www.smashingmagazine.com/) and try to make your project look like that.
- The nav bar should look like this 
nav
- Kindly make the project look like a clone 
gray

- Let us apply the shades of gray. The color for each section. 
apply
- Kindly make the requested changes and submit another code review.

[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

Happy coding :slightly_smiling_face:

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project is not complete.

**Comment by pelzolga123** [comment]
## Hi Team!  
### You haven't fixed what previous TSE required, please make that changes and then submit for review again. You are not required to add animation or pictures. But you need to create the same structure with all sections Smashing Magazine has. 

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by jabichris** [comment]
Hi @pelzolga123 and @addod19. Thank you very much for the feedback. But I am wondering If on this project we are supposed to do a clone or grayscale heat map. 

Screen Shot 2020-01-21 at 00 24 33

**Comment by pelzolga123** [comment]
> Hi @pelzolga123 and @addod19. Thank you very much for the feedback. But I am wondering If on this project we are supposed to do a clone or grayscale heat map.
> 
> Screen Shot 2020-01-21 at 00 24 33
You don't need to create ecsect copy of smashing magazine, but you need to replicate the structure of it. It means every section from original website should be present.

**Review by nikasulo — APPROVED** [review]
# WOW! So shiny! 
Congratulations @jabichris and @addod19, you have done a really fantastic job and you may merge :rocket:. See you at the very top! :smile: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
